### ISSUE TITLE
not working on initial render

### ISSUE THREAD

**Issue by maxschulmeister** [rguanghui/vue-sticky#10]
the directive is not working on initial render, gives a strange behaviour – it just sticks somewhere to the page not the viewport.

on route update it works fine, any idea why?

i'm using it with nuxt.js like so:

```
import Vue from 'vue'
import VueSticky from 'vue-sticky'

Vue.directive('sticky', VueSticky)
```

**Comment by iqingting** [comment]
hi, can you provide a online demo ?

**Comment by maxschulmeister** [comment]
if it works for you on initial render, it most likely is an issue with nuxt.js and/or SSR
will give feedback when i use the directive in a "normal" vue instance.

**Comment by citricacid-pl** [comment]
I have very same issue. On initial render it is not working. Any update on the issue?

**Comment by citricacid-pl** [comment]
Strange thing is it sets styles and classes but not working as intended. (Tested on Mac on Chrome)
