### ISSUE TITLE
Add 'active' class when in sticky mode

### ISSUE THREAD

**Issue by georgefeast** [rguanghui/vue-sticky#19]
It would be great if we could pass a class name as a prop to be applied to the el when in sticky mode i.e. when the header is sticky it applies class 'active' so we can make styling changes to background color etc. Unless there's some way to do this already that I'm missing?

**Comment by 0m4r** [comment]
@georgefeast this should be solved with the latest updates!

**Comment by 0m4r** [comment]
@rguanghui are you publishing a new npm version to make the fix available?
here it is still @3.3.3 https://www.npmjs.com/package/vue-sticky

**Comment by iqingting** [comment]
@0m4r @georgefeast 

this plugin is to be consistent with the css native sticky.

as the native css not provide the api which like `sticky-change`

so, this plugin will not do this thing to follow the css sticky

**Comment by 0m4r** [comment]
well, you have approved earlier a PR that actually introduces it....
